// <auto-generated />
using System;
using ClaimsModule.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaimsModule.Persistence.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    partial class ClaimsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClaimsModule.Domain.Entities.CauseOfLossCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerilCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CauseOfLossCodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-000000000001"),
                            Code = "COL-FIRE",
                            IsActive = true,
                            Name = "Fire",
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Property",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-000000000002"),
                            Code = "COL-FLOOD",
                            IsActive = true,
                            Name = "Flood",
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Weather",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-000000000003"),
                            Code = "COL-THEFT",
                            IsActive = true,
                            Name = "Theft",
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Crime",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-000000000004"),
                            Code = "COL-VEH-COL",
                            IsActive = true,
                            Name = "Vehicle Collision",
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Auto",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-000000000005"),
                            Code = "COL-VEH-COMP",
                            IsActive = true,
                            Name = "Vehicle Comprehensive",
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Auto",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-000000000006"),
                            Code = "COL-LIAB",
                            IsActive = true,
                            Name = "Third Party Liability",
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Liability",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-000000000007"),
                            Code = "COL-EQUIP",
                            IsActive = true,
                            Name = "Equipment Breakdown",
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Equipment",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-000000000008"),
                            Code = "COL-WIND",
                            IsActive = true,
                            Name = "Wind / Storm",
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Weather",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-000000000009"),
                            Code = "COL-INJURY",
                            IsActive = true,
                            Name = "Bodily Injury",
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Liability",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-00000000000a"),
                            Code = "COL-OTHER",
                            IsActive = true,
                            Name = "Other / Unknown",
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "General",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("AssignedHandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClosureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagerOverrideForReserves")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ReportedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("OrganisationId", "ClaimNumber")
                        .IsUnique();

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimAuditLog", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimDocuments", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimNumberSequence", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("LastSequence")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OrganisationId", "Year");

                    b.ToTable("ClaimNumberSequences", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartyRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimParties", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimReserveComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimReserveComponents", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimRiskObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DamageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimRiskObjects", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimStatusTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequiredPermission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ClaimStatusTransitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000001"),
                            FromStatus = "Draft",
                            ToStatus = "Open"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000002"),
                            FromStatus = "Open",
                            ToStatus = "UnderInvestigation"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000003"),
                            FromStatus = "Open",
                            ToStatus = "PendingPayment"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000004"),
                            FromStatus = "Open",
                            ToStatus = "Closed"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000005"),
                            FromStatus = "Open",
                            ToStatus = "Withdrawn"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000006"),
                            FromStatus = "UnderInvestigation",
                            ToStatus = "Open"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000007"),
                            FromStatus = "UnderInvestigation",
                            ToStatus = "PendingPayment"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000008"),
                            FromStatus = "UnderInvestigation",
                            ToStatus = "Closed"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-000000000009"),
                            FromStatus = "UnderInvestigation",
                            ToStatus = "Withdrawn"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-00000000000a"),
                            FromStatus = "PendingPayment",
                            ToStatus = "Closed"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-00000000000b"),
                            FromStatus = "Closed",
                            RequiredPermission = "supervisor",
                            ToStatus = "Reopened"
                        },
                        new
                        {
                            Id = new Guid("50000001-0001-0001-0001-00000000000c"),
                            FromStatus = "Reopened",
                            ToStatus = "Open"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimValidationIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimValidationIssues", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.LossEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CauseOfLossCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("EstimatedLossAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LossDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LossDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LossLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PoliceReportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReportDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.ToTable("LossEvents", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverageTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.ToTable("Policies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000001-0001-0001-0001-000000000001"),
                            ClientName = "Meridian Transport LLC",
                            CoverageTypes = "Vehicle,Cargo",
                            EffectiveDate = new DateOnly(2024, 1, 1),
                            ExpirationDate = new DateOnly(2026, 12, 31),
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2024-001001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("40000001-0001-0001-0001-000000000002"),
                            ClientName = "Harborview Properties Inc",
                            CoverageTypes = "Property,Liability",
                            EffectiveDate = new DateOnly(2024, 6, 1),
                            ExpirationDate = new DateOnly(2026, 5, 31),
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2024-001002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("40000001-0001-0001-0001-000000000003"),
                            ClientName = "Coastal Builders Group",
                            CoverageTypes = "Property,Equipment",
                            EffectiveDate = new DateOnly(2025, 3, 1),
                            ExpirationDate = new DateOnly(2027, 2, 28),
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2025-002001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("40000001-0001-0001-0001-000000000004"),
                            ClientName = "Stanton Medical Group",
                            CoverageTypes = "Liability,Vehicle",
                            EffectiveDate = new DateOnly(2025, 1, 1),
                            ExpirationDate = new DateOnly(2026, 12, 31),
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2025-002002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("40000001-0001-0001-0001-000000000005"),
                            ClientName = "Archived Corp",
                            CoverageTypes = "Property",
                            EffectiveDate = new DateOnly(2020, 1, 1),
                            ExpirationDate = new DateOnly(2021, 12, 31),
                            OrganisationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2023-000099",
                            Status = "Expired"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ReserveHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChangeSequence")
                        .HasColumnType("int");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("NewBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostingJobId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PreviousBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReserveComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ReserveComponentId");

                    b.ToTable("ReserveHistory", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Claim", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimAuditLog", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimDocument", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimParty", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithMany("Parties")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimReserveComponent", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithMany("ReserveComponents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimRiskObject", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithMany("RiskObjects")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimValidationIssue", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithMany("ValidationIssues")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.LossEvent", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithOne("LossEvent")
                        .HasForeignKey("ClaimsModule.Domain.Entities.LossEvent", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ReserveHistory", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimsModule.Domain.Entities.ClaimReserveComponent", "ReserveComponent")
                        .WithMany("History")
                        .HasForeignKey("ReserveComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("ReserveComponent");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Claim", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Documents");

                    b.Navigation("LossEvent");

                    b.Navigation("Parties");

                    b.Navigation("ReserveComponents");

                    b.Navigation("RiskObjects");

                    b.Navigation("ValidationIssues");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimReserveComponent", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
